import type { Express } from "express";
import type { Server } from "http";
import { storage } from "./storage";
import { api } from "@shared/routes";

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  
  app.get(api.grants.list.path, async (req, res) => {
    const allGrants = await storage.getGrants();
    res.json(allGrants);
  });

  app.get(api.faculty.list.path, async (req, res) => {
    const allFaculty = await storage.getFaculty();
    res.json(allFaculty);
  });

  app.get('/api/forge/:grantId', async (req, res) => {
    const { grantId } = req.params;
    const { role, year, program } = req.query;
    
    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    try {
      // Fetch grant and faculty from database
      const grant = await storage.getGrantById(parseInt(grantId));
      if (!grant) {
        res.write(`data: ${JSON.stringify({ 
          step: "Grant not found", 
          done: true, 
          error: true 
        })}\n\n`);
        return res.end();
      }
      
      const facultyList = await storage.getFaculty();
      
      // Build payload for agent service
      const payload = {
        grantId: grant.id,
        grantName: grant.name,
        matchCriteria: grant.matchCriteria,
        eligibility: grant.eligibility,
        userProfile: {
          role: role as string,
          year: year as string,
          program: program as string
        },
        facultyList: facultyList.map(f => ({
          name: f.name,
          department: f.department,
          expertise: f.expertise,
          imageUrl: f.imageUrl,
          bio: f.bio
        }))
      };
      
      // Try to invoke agent service with fallback to mock
      try {
        const { invokeAgentPipeline } = await import('./agent-client.js');
        
        for await (const jsonLine of invokeAgentPipeline(payload)) {
          if (jsonLine.done) {
            // Final message with result
            res.write(`data: ${JSON.stringify({
              step: "Complete",
              done: true,
              result: jsonLine.output
            })}\n\n`);
          } else {
            // Progress message
            res.write(`data: ${JSON.stringify({
              step: `${jsonLine.agent}: ${jsonLine.step}`,
              done: false
            })}\n\n`);
          }
        }
      } catch (agentError) {
        // Fallback to mock steps
        console.warn('Agent service unreachable, falling back to mock steps:', agentError);
        
        const mockSteps = [
          "SourcingAgent: Extracting CV data...",
          "MatchmakingAgent: Analyzing match criteria...",
          "MatchmakingAgent: Checking FSU policies...",
          "CollaboratorAgent: Finding relevant faculty...",
          "DraftingAgent: Generating proposal draft..."
        ];
        
        for (const step of mockSteps) {
          res.write(`data: ${JSON.stringify({ step, done: false })}\n\n`);
          await new Promise(resolve => setTimeout(resolve, 800));
        }
        
        // Mock result
        const mockResult = {
          proposalDraft: `Mock proposal for ${grant.name}. This is a placeholder generated by the fallback system.`,
          collaborators: [
            { name: "Dr. Smith", department: "Computer Science", expertise: "AI", relevanceScore: 85 }
          ],
          matchScore: 75,
          matchJustification: "Mock justification based on profile alignment",
          complianceChecklist: [
            { task: "Submit RAMP form", category: "RAMP", status: "yellow" }
          ]
        };
        
        res.write(`data: ${JSON.stringify({
          step: "Complete",
          done: true,
          result: mockResult
        })}\n\n`);
      }
      
      res.end();
    } catch (error) {
      console.error('Error in forge endpoint:', error);
      res.write(`data: ${JSON.stringify({
        step: "An error occurred",
        done: true,
        error: true
      })}\n\n`);
      res.end();
    }

    req.on('close', () => {
      // Cleanup if needed
    });
  });

  // Seed DB with mock data for the prototype
  const existingGrants = await storage.getGrants();
  if (existingGrants.length === 0) {
    const grantsData = [
      { name: "NSF GRFP", targetAudience: "Grad Students", eligibility: "Year 1-2 PhD", matchCriteria: "STEM, Social Science, Research", internalDeadline: "72 hours before Oct deadline" },
      { name: "FSU IDEA Grant", targetAudience: "Undergrads", eligibility: "Soph/Junior", matchCriteria: "Innovation, Inquiry, Mentorship", internalDeadline: "72 hours before rolling deadline" },
      { name: "FSU CRC Planning", targetAudience: "Faculty", eligibility: "Tenure-Track", matchCriteria: "Interdisciplinary, Seed Funding", internalDeadline: "72 hours before Feb/Sept deadline" },
      { name: "McKnight Doctoral", targetAudience: "PhD Students", eligibility: "Year 1-3", matchCriteria: "Diversity, Retention, Research", internalDeadline: "72 hours before Jan deadline" },
      { name: "NSF CAREER", targetAudience: "Junior Faculty", eligibility: "Pre-Tenure", matchCriteria: "Integration, Education, Research", internalDeadline: "72 hours before July deadline" }
    ];
    for (const g of grantsData) await storage.createGrant(g);
  }

  const existingFaculty = await storage.getFaculty();
  if (existingFaculty.length === 0) {
    const facultyData = [
      { 
        name: "Dr. Sarah Chen", 
        department: "Computer Science", 
        expertise: "AI, Machine Learning", 
        imageUrl: "https://i.pravatar.cc/150?u=sarah",
        bio: "Dr. Chen focuses on neural architecture search and ethical AI frameworks. She has secured over $5M in NSF funding since 2018."
      },
      { 
        name: "Dr. Marcus Johnson", 
        department: "Engineering", 
        expertise: "Robotics, Control Systems", 
        imageUrl: "https://i.pravatar.cc/150?u=marcus",
        bio: "Specializing in autonomous marine robotics, Dr. Johnson leads the FSU Marine Robotics Lab with a focus on environmental monitoring."
      },
      { 
        name: "Dr. Elena Rodriguez", 
        department: "Information", 
        expertise: "Human-Computer Interaction", 
        imageUrl: "https://i.pravatar.cc/150?u=elena",
        bio: "Dr. Rodriguez researches accessibility in digital interfaces, particularly for neurodivergent populations in educational settings."
      }
    ];
    for (const f of facultyData) await storage.createFaculty(f);
  }

  return httpServer;
}
