#!/usr/bin/env python3
"""
Generate .env file for Express Backend

Creates environment variables from AWS infrastructure configuration.
"""

import json
import argparse
import sys

def main():
    parser = argparse.ArgumentParser(description='Generate .env file for Express backend')
    parser.add_argument('--output', default='.env.aws', help='Output file path')
    args = parser.parse_args()
    
    print("=" * 60)
    print("FundingForge - Generate Environment Variables")
    print("=" * 60)
    print()
    
    # Load all configurations
    try:
        with open('agent_config.json', 'r') as f:
            agent_config = json.load(f)
        with open('iam_config.json', 'r') as f:
            iam_config = json.load(f)
    except FileNotFoundError as e:
        print(f"❌ Error: Configuration file not found: {e.filename}")
        sys.exit(1)
    
    # Try to load optional configs
    kb_config = None
    try:
        with open('knowledge_base_config.json', 'r') as f:
            kb_config = json.load(f)
    except FileNotFoundError:
        pass
    
    lambda_config = None
    try:
        with open('lambda_config.json', 'r') as f:
            lambda_config = json.load(f)
    except FileNotFoundError:
        pass
    
    # Generate .env content
    env_lines = [
        "# AWS Bedrock Configuration",
        "# Generated by FundingForge setup scripts",
        "",
        "# AWS Region",
        f"AWS_REGION={agent_config['region']}",
        "",
        "# Bedrock Supervisor Agent",
        f"BEDROCK_SUPERVISOR_AGENT_ID={agent_config['agents']['supervisor']['id']}",
        f"BEDROCK_AGENT_ALIAS_ID={agent_config['agents']['supervisor']['alias_id']}",
        "",
        "# Sub-Agents (for reference)",
        f"BEDROCK_SOURCING_AGENT_ID={agent_config['agents']['sourcing']['id']}",
        f"BEDROCK_MATCHMAKING_AGENT_ID={agent_config['agents']['matchmaking']['id']}",
        f"BEDROCK_COLLABORATOR_AGENT_ID={agent_config['agents']['collaborator']['id']}",
        f"BEDROCK_DRAFTING_AGENT_ID={agent_config['agents']['drafting']['id']}",
        "",
        "# Feature Flags",
        "USE_BEDROCK_AGENTS=true",
        "COMPARE_IMPLEMENTATIONS=false",
        "",
    ]
    
    # Add Knowledge Base config if available
    if kb_config:
        env_lines.extend([
            "# Knowledge Base",
            f"KNOWLEDGE_BASE_ID={kb_config['knowledge_base']['id']}",
            f"KNOWLEDGE_BASE_DATA_SOURCE_ID={kb_config['knowledge_base']['data_source_id']}",
            f"S3_KNOWLEDGE_BASE_BUCKET={kb_config['s3_bucket']}",
            "",
        ])
    
    # Add Lambda config if available
    if lambda_config:
        env_lines.extend([
            "# Lambda Functions (for reference)",
            f"LAMBDA_FACULTY_RANKING_ARN={lambda_config['functions']['faculty_ranking']['arn']}",
            f"LAMBDA_COMPLIANCE_CHECKER_ARN={lambda_config['functions']['compliance_checker']['arn']}",
            f"LAMBDA_PROPOSAL_FORMATTER_ARN={lambda_config['functions']['proposal_formatter']['arn']}",
            "",
        ])
    
    # Add AWS credentials placeholder
    env_lines.extend([
        "# AWS Credentials (set these based on your environment)",
        "# Option 1: Use AWS CLI profile (recommended for local development)",
        "# AWS_PROFILE=your-profile-name",
        "",
        "# Option 2: Use explicit credentials (not recommended for production)",
        "# AWS_ACCESS_KEY_ID=your-access-key",
        "# AWS_SECRET_ACCESS_KEY=your-secret-key",
        "",
        "# Option 3: Use IAM role (recommended for production)",
        "# No credentials needed - Express will use EC2/ECS instance role",
        "",
    ])
    
    # Write to file
    with open(args.output, 'w') as f:
        f.write('\n'.join(env_lines))
    
    print(f"✓ Generated environment file: {args.output}")
    print()
    print("Configuration summary:")
    print(f"  Region: {agent_config['region']}")
    print(f"  Supervisor Agent ID: {agent_config['agents']['supervisor']['id']}")
    print(f"  Alias ID: {agent_config['agents']['supervisor']['alias_id']}")
    if kb_config:
        print(f"  Knowledge Base ID: {kb_config['knowledge_base']['id']}")
    print()
    print("Next steps:")
    print(f"  1. Review the generated file: {args.output}")
    print("  2. Add AWS credentials (AWS_PROFILE or AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY)")
    print("  3. Copy to your project root:")
    print(f"     cat {args.output} >> ../../.env")
    print("  4. Start implementing Developer B tasks (Express backend)")
    print()

if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print(f"\n❌ Error: {e}", file=sys.stderr)
        sys.exit(1)
